export const highwayTypes = {
  FETCH_HIGHWAYS_SUCCESS: 'FETCH_HIGHWAYS_SUCCESS',
  FETCH_HIGHWAYS_PENDING: 'FETCH_HIGHWAYS_PENDING',
  FETCH_HIGHWAYS_ERROR: 'FETCH_HIGHWAYS_ERROR',
  FETCH_ROADWORKS_SUCCESS: 'FETCH_ROADWORKS_SUCCESS',
  FETCH_ROADWORKS_PENDING: 'FETCH_ROADWORKS_PENDING',
  FETCH_ROADWORKS_ERROR: 'FETCH_ROADWORKS_ERROR',
  SELECTED_HIGHWAY: 'SELECTED_HIGHWAY',
  ADD_TO_FAVORITES: 'ADD_TO_FAVORITES',
  REMOVE_FROM_FAVORITES: 'REMOVE_FROM_FAVORITES',
  MODIFY_SELECTED_HIGHWAY: 'MODIFY_SELECTED_HIGHWAY',

}

